backend:
  name: github
  repo: wevial/genesis
  branch: main
  base_url: https://genesis-cms-auth.kovial.workers.dev

media_folder: src/assets
public_folder: /src/assets

collections:
  - name: blog
    label: Blog posts
    label_singular: Blog post
    folder: src/content/blog
    create: true
    slug: '{{slug}}'
    extension: md
    format: frontmatter
    sortable_fields: [date, title]
    fields:
      - { name: title, label: Title, widget: string }
      - name: date
        label: Date
        widget: datetime
        format: YYYY-MM-DD
        date_format: YYYY-MM-DD
        time_format: false
      - { name: description, label: Description, widget: string, required: false }
      - { name: draft, label: Draft, widget: boolean, default: false }
      - { name: body, label: Body, widget: markdown }
